### ISSUE TITLE
Upgrade to React 16.0.0

### ISSUE THREAD

**Issue by ioan-ungurean** [LINKIWI/react-duo-web#1]
I tried to use this package with the newly release React 16.0.0 and this error pops up:

![image](https://user-images.githubusercontent.com/25197517/30902799-46e235d6-a375-11e7-9d6d-655ba2d08b09.png)

**Comment by jnardone** [comment]
How does this work when package.json still says 

```
  "peerDependencies": {
    "react": "^15.4.1"
}
```

I still get NPM warnings abou "react-duo-web@1.0.0 requires a per of react@^15.4.1 but none is instaled"...
